import type { Metadata } from "next";
import { CTASection, FeatureCard, Page, PageHero, Prose, Section, TwoColumnSection } from "@/components/content";

export const metadata: Metadata = { title: "About Comikage — Business-First Website & Application Development", description: "Comikage is a business-first technology studio helping founders and growing companies build websites, business applications, and AI-powered digital systems by first understanding the business." };
const builds = [["Business websites", "Professional websites, landing pages, service pages, and digital presence systems for companies that need to communicate clearly and build credibility."], ["Business applications", "Internal dashboards, admin panels, client portals, CRM-style systems, approval workflows, project tracking tools, and custom applications for businesses that have outgrown spreadsheets."], ["AI and automation", "Practical AI-assisted workflows, internal knowledge tools, document search systems, lead qualification flows, chatbot interfaces, and automation systems that reduce repetitive work."]];

export default function About() { return <Page><PageHero eyebrow="About Comikage" title="Built for businesses that need more than a developer." body={<><p>Comikage is a business-first technology studio that helps founders, startups, and growing companies build websites, business applications, and AI-powered digital systems.</p><p className="font-semibold text-ink">But we do not start with code. We start by understanding the business.</p></>} />
  <Section title="Why Comikage exists" surface><Prose><p>Many business owners approach web developers expecting a complete digital solution. Instead, they are often asked to provide everything themselves: the content, structure, positioning, page flow, calls-to-action, and sometimes even the business logic.</p><p>The developer then builds what is provided. That may produce a website, but it rarely produces clarity.</p><p>Comikage works differently. We help business owners think through the digital requirement before development begins—shaping the structure, refining the messaging, mapping the customer journey, and identifying whether the business needs a website, application, automation, or internal system.</p></Prose></Section>
  <Section eyebrow="Operator perspective" title="Founder-led thinking"><TwoColumnSection><Prose><p>Every project is approached with questions that go beyond design and development:</p><ul className="list-disc space-y-2 pl-5"><li>What does the business need to communicate?</li><li>What should a customer understand before making an enquiry?</li><li>Where are manual workflows slowing the team down?</li><li>Which processes can be simplified through software?</li><li>What should be built now, and what should be deferred?</li></ul></Prose><Prose><p>This perspective matters because digital projects fail when technology is separated from business reality.</p><p>A beautiful website without trust, enquiries, or clarity is not enough. An application that ignores real workflows becomes another unused tool. AI without a clear operational use case becomes a gimmick.</p><p>Comikage focuses on practical digital systems that support actual business outcomes.</p></Prose></TwoColumnSection></Section>
  <Section title="What we build" surface><div className="grid gap-5 lg:grid-cols-3">{builds.map(([t,d],i)=><FeatureCard key={t} title={t} number={`0${i+1}`}>{d}</FeatureCard>)}</div></Section>
  <Section title="How we work"><Prose><p>Every engagement begins with understanding. We clarify the business model, audience, offer, workflow, constraints, and desired outcome. From there, we define the right digital scope.</p><p>Sometimes the right first step is a focused website or landing page. Sometimes it is a business application. Sometimes the smartest recommendation is to start smaller and build in phases.</p><p>That is why Comikage does not sell technology as a commodity. We help define what should be built, why it should be built, and how it should support the business.</p></Prose></Section>
  <Section title="Who Comikage is for" surface><Prose><p>Comikage is for founders, consultants, professional firms, service businesses, and growing companies that want a technology partner who can think with them.</p><p>It is especially useful for businesses that need a better digital presence or internal system, but are not yet clear on the exact structure, content, features, or technical approach.</p><p>If you already know exactly what to build, we can help execute it. If you only know the business problem, we can help define the solution.</p></Prose></Section>
  <CTASection title="Build technology around your business." body="If you are planning a website, business application, client portal, dashboard, or AI-powered workflow, Comikage can help you clarify the right first step." label="Discuss a Project" /></Page>; }
