import type { ReactNode } from "react";
import { ArrowRight, Check } from "./icons";
import { Footer, Header } from "./site-shell";

export function Page({ children }: { children: ReactNode }) { return <><Header /><main>{children}</main><Footer /></>; }
export function PageHero({ eyebrow, title, body }: { eyebrow: string; title: string; body: ReactNode }) { return <section className="shell py-20 sm:py-24 lg:py-32"><p className="eyebrow">{eyebrow}</p><h1 className="mt-6 max-w-5xl text-4xl font-semibold leading-[1.05] tracking-[-0.045em] sm:text-6xl lg:text-[68px]">{title}</h1><div className="body-copy mt-7 max-w-3xl space-y-5">{body}</div></section>; }
export function Section({ eyebrow, title, children, surface = false, id }: { eyebrow?: string; title: string; children: ReactNode; surface?: boolean; id?: string }) { return <section id={id} className={`border-t border-line py-20 lg:py-28 ${surface ? "bg-white" : ""}`}><div className="shell">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2 className="section-title">{title}</h2><div className="mt-10">{children}</div></div></section>; }
export function TwoColumnSection({ children }: { children: ReactNode }) { return <div className="grid gap-8 lg:grid-cols-2 lg:gap-16">{children}</div>; }
export function FeatureCard({ title, children, number }: { title: string; children?: ReactNode; number?: string }) { return <article className="card p-7 sm:p-8">{number && <span className="text-xs font-semibold text-accent">{number}</span>}<h3 className="mt-6 text-xl font-semibold tracking-tight">{title}</h3>{children && <div className="mt-4 text-sm leading-7 text-muted">{children}</div>}</article>; }
export function ServiceCard({ title, children, href }: { title: string; children: ReactNode; href: string }) { return <a href={href} className="card group flex min-h-72 flex-col p-8"><span className="text-xs font-semibold uppercase tracking-[.15em] text-accent">Service</span><h3 className="mt-auto pt-12 text-2xl font-semibold tracking-tight">{title}</h3><p className="mt-4 leading-7 text-muted">{children}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-ink group-hover:text-accent">Explore service <ArrowRight /></span></a>; }
export function Checklist({ items, columns = 2 }: { items: string[]; columns?: 1 | 2 | 3 }) { const cls = columns === 3 ? "lg:grid-cols-3" : columns === 2 ? "md:grid-cols-2" : ""; return <ul className={`grid gap-3 ${cls}`}>{items.map(item => <li key={item} className="flex gap-3 rounded-xl border border-line bg-white p-4 text-sm"><Check className="mt-0.5 shrink-0 text-accent" />{item}</li>)}</ul>; }
export function PackageCard({ title, price, description, items, featured }: { title: string; price: string; description: string; items: string[]; featured?: boolean }) { return <article className={`flex flex-col rounded-2xl border bg-white p-8 ${featured ? "border-accent shadow-soft" : "border-line shadow-card"}`}><h3 className="text-xl font-semibold">{title}</h3><p className="mt-6 text-3xl font-semibold tracking-tight">{price}</p><p className="mt-5 text-sm leading-6 text-muted">{description}</p><div className="my-6 h-px bg-line" /><Checklist items={items} columns={1} /></article>; }
export function CTASection({ title, body, label, subject = "Project Enquiry" }: { title: string; body?: string; label: string; subject?: string }) { return <section className="shell py-16 lg:py-24"><div className="rounded-[28px] bg-accent px-6 py-16 text-center text-white sm:px-12 lg:py-20"><h2 className="mx-auto max-w-3xl text-3xl font-semibold tracking-[-.035em] sm:text-5xl">{title}</h2>{body && <p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-blue-100">{body}</p>}<a href={`mailto:hello@comikage.com?subject=${encodeURIComponent(subject)}`} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-4 text-sm font-semibold text-accent hover:bg-ink hover:text-white">{label}<ArrowRight /></a></div></section>; }
export function Prose({ children }: { children: ReactNode }) { return <div className="max-w-3xl space-y-6 text-base leading-8 text-muted sm:text-lg">{children}</div>; }
